var ETOILES = [
    "Abrachaleus",
    "Abyssus Aquae",
    "Acamar",
    "Achernar",
    "Achird",
    "Acrab",
    "Acrux",
    "Acubens",
    "Adara",
    "Adhaféra",
    "Adhara",
    "Adhil",
    "Adib",
    "Adkhaféra",
    "Agéna",
    "Aïn",
    "Aïn al Rami",
    "Ak",
    "Akhamar",
    "Akhénar",
    "Akrab",
    "Akruks",
    "Akubens",
    "Aladfar",
    "Alamak",
    "Al Anchat al Nahr",
    "Al Anf",
    "Al Anz",
    "Al'araf",
    "Alaraf",
    "Alaraph",
    "Bêta Virginis",
    "Epsilon Virginis",
    "Al Ashfar",
    "Mu Leonis",
    "Al Athfar",
    "Alathfar",
    "Al Atik",
    "Al Baldah",
    "Albaldah",
    "Al Bali",
    "Al'bali",
    "Albali",
    "Al'biréo",
    "Albiréo",
    "Alcaïd",
    "Al Chiba",
    "Al'chiba",
    "Alchiba",
    "Alchita",
    "Al'cor",
    "Alcor",
    "Alcyone",
    "Al'danab",
    "Al'débaran",
    "Aldébaran",
    "Aldéraïmin",
    "Al'déramin",
    "Aldéramin",
    "Aldhafara",
    "Aldhaféra",
    "Al Dhanab",
    "Al Dhiba",
    "Aldhibah",
    "Al Dhibaïn Prior",
    "Al Dhiha",
    "Aldib",
    "Al'dzhabkhakh",
    "Al'fakka",
    "Al'faret",
    "Al'farg",
    "Al'fard",
    "Alfard",
    "Alfecca Meridiana",
    "Al'fekka",
    "Alfekka Meridiana",
    "Al'férats",
    "Al'firk",
    "Alfirk",
    "Alga",
    "Algébar",
    "Algédi",
    "Algéiba",
    "Al'génib",
    "Gamma Pegasi",
    "Algénib",
    "Al'génubi",
    "Algénubi",
    "Al'giéba",
    "Al'gejba",
    "Al Giéba",
    "Algiéba",
    "Algiedi Prima",
    "Algiedi Secunda",
    "Al'gol'",
    "Algol",
    "Algol'",
    "Algomeyla",
    "Algomeysa",
    "Al'gorab",
    "Algorab",
    "Algoras",
    "Algorel",
    "Algores",
    "Alhajoth",
    "Al Hammam",
    "Alhéna",
    "Aliath",
    "Alifa al Farkadain",
    "Aliot",
    "Alioth",
    "Al Kab",
    "Al Kaff al Jidhmah",
    "Al Kafzah al Thaniyah",
    "Alkaïd",
    "Al Kalb al Asad",
    "Al Kalb al Raï",
    "Alkalurops",
    "Al'kand",
    "Alkaphrah",
    "Al'kes",
    "Alkes",
    "Al'khajot",
    "Al'khéka",
    "Al'khéna",
    "Al Kirdah",
    "Alkurhah",
    "Almaach",
    "Almaak",
    "Almaaz",
    "Almach",
    "Al'mak",
    "Almak",
    "Al Mankib",
    "Al Minliar al Asad",
    "Al Minliar al Ghurab",
    "Al Minliar al Shuja",
    "Al Mizar",
    "Almucédie",
    "Almurédin",
    "Al Na'ir",
    "Al Naïr",
    "Al'naïr",
    "Alnaïr",
    "Al Nasl",
    "Alnasl",
    "Alnath",
    "Alnihan",
    "Alnilam",
    "Alnitam",
    "Alnitah",
    "Al'nitak",
    "Alnitak",
    "Al Niyat",
    "Tau Scorpii",
    "Alniyat",
    "Alphakka",
    "Alphard",
    "Alphart",
    "Alphecca",
    "Alphekka",
    "Alphérat",
    "Alphératz",
    "Alphirk",
    "Al'raï",
    "Alraï",
    "Al Rakis",
    "Al Ras al Asad al Janubiyyah",
    "Alrescha",
    "Al Risha",
    "Alrischa",
    "Al'risha",
    "Alrisha",
    "Alruccaba",
    "Alruccabah",
    "Al'rukaba",
    "Al Rukbah al Dajajah",
    "Al'sabik",
    "Alsafi",
    "Alsahm",
    "Al Salam al Nakah",
    "Alschaïrn",
    "Alshaïn",
    "Alsciaukat",
    "Al Sharataïn",
    "Alshat",
    "Alshémali",
    "Alsuhail",
    "Al Suhail al Muhlif",
    "Al Suhail al Wazn",
    "Al' Sukhal",
    "Al Tarf",
    "Altarf",
    "Al'taïr",
    "Altaïr",
    "Al'taïs",
    "Altaïs",
    "Alterf",
    "Al'tsiona",
    "Al'tsione",
    "Aludra",
    "Alula Australe",
    "Alula Australis",
    "Alula Boreale",
    "Alula Borealis",
    "Alwaïd",
    "Alwazl",
    "Alwazn",
    "Al Wazor",
    "Alya",
    "Alzirr",
    "Ancha",
    "Anchat",
    "Angetenar",
    "Ankaa",
    "Anser",
    "Antarès",
    "Antécanis",
    "Anwar al Farkadaïn",
    "Apollo",
    "Arcturus",
    "Arich",
    "Arided",
    "Aridif",
    "Arietis",
    "Arkab",
    "Bêta2 Sagittarii",
    "Arkab Posterior",
    "Arkab Prior",
    "Arktur",
    "Arm",
    "Arneb",
    "Arraï",
    "Arrakis",
    "Arrioph",
    "Ascella",
    "Aschere",
    "Aschéré",
    "Asellus Australis",
    "Asellus Borealis",
    "Asellus Primus",
    "Asellus Secundus",
    "Asellus Tertius",
    "Asgard",
    "Ashtaroth",
    "Askéla",
    "Asmidiske",
    "Aspidiske",
    "Astérion",
    "Asteropa",
    "Astérope",
    "Astsella",
    "Asuia",
    "Ataïr",
    "Athafi",
    "Ati",
    "Atik",
    "Atiks",
    "Atlas",
    "Atria",
    "Alpha Trianguli Australis",
    "Auva",
    "Avior",
    "Azelfafage",
    "Azha",
    "Azimech",
    "Azmidiske",
    "Baham",
    "Bakham",
    "Baten Kaitos",
    "Baten Kajtos",
    "Bécrux",
    "Beemin",
    "Beïd",
    "Békruks",
    "Bellatriks",
    "Bellatrix",
    "Benetnasch",
    "Benetnash",
    "Beteiguex",
    "Betel'gejze",
    "Bételgeuse",
    "Bételgeuze",
    "Betelguex",
    "Biham",
    "Boteïn",
    "Botejn",
    "Brachium",
    "Caïam",
    "Cajam",
    "Calx",
    "Canicula",
    "Canopus",
    "Capella",
    "Caph",
    "Caput Trianguli",
    "Castor",
    "Cébalraï",
    "Céginus",
    "Phi Bootis",
    "Celaeno",
    "Célaéno",
    "Celb-al-Raï",
    "Céléno",
    "Celieno",
    "Célieno",
    "Céline",
    "Cexing",
    "Chaph",
    "Chara",
    "Beta Canum Venaticorum",
    "Cheleb",
    "Chertan",
    "Chort",
    "Clava",
    "Cor Caroli",
    "Cor Hydrae",
    "Cor Leonis",
    "Cornu",
    "Cor Serpentis",
    "Cor Scorpii",
    "Cor Tauri",
    "Coxa",
    "Cujam",
    "Cursa",
    "Cymbae",
    "Cygnus X-1",
    "Cynosura",
    "Dabih",
    "Dabikh",
    "Dana",
    "Déneb",
    "Epsilon Aquilae",
    "Êta Ceti",
    "Zêta Aquilae",
    "Deneb Aleet",
    "Deneb Al'gedi",
    "Delta Capricorni",
    "Deneb Algedi",
    "Deneb Algenubi",
    "Deneb Algiedi",
    "Deneb al Okab Australis",
    "Deneb al Okab Borealis",
    "Deneb al' Shemali",
    "Deneb Cygni",
    "Deneb Dulfim",
    "Deneb ehl' Del'fini",
    "Deneb el Adige",
    "Deneb el Delphinus",
    "Deneb el Okab",
    "Deneb Kaitos",
    "Deneb Kaitos Schemali",
    "Deneb Kaitos Al Shamaliyy",
    "Deneb Kajtos",
    "Deneb Okab",
    "Dénébola",
    "Dhalim",
    "Dheneb",
    "Diadème",
    "Difda",
    "Difda al Auwel",
    "Difda al Thani",
    "Dikhabda",
    "Diphda",
    "Dirakh",
    "Dschubba",
    "Dsiban",
    "Dubb",
    "Dubé",
    "Dubhé",
    "Dubkhé",
    "Duhr",
    "Dzhanakh",
    "Dzhubba",
    "Dziban",
    "Ed Asich",
    "Edasich",
    "Eldsib",
    "Ehlekctra",
    "Ehl'gomajza",
    "Ehl'nat",
    "Ehl'natkh",
    "Ehlyakrab",
    "Ehrakis",
    "Ehtamin",
    "Elacrab",
    "Eldsich",
    "Électre",
    "Electra",
    "Elgébar",
    "El Ghoul",
    "Elgomaïsa",
    "Elkeïd",
    "El khereb",
    "Elkhiffa Australis",
    "El Koprah",
    "El Mara el Musalsela",
    "El Mélik",
    "Elmuthalleth",
    "El Nasl",
    "El Nath",
    "Bêta Tauri",
    "Elnath",
    "El Rakis",
    "El Rischa",
    "Eltanin",
    "Enf",
    "Énif",
    "Énir",
    "Épi",
    "Érakis",
    "Er Raï",
    "Erraï",
    "Errakis",
    "Étamin",
    "Étanin",
    "Étoile de Barnard",
    "Étoile de Cayrel",
    "Étoile de Kapteyn",
    "Étoile de Krzeminski",
    "Étoile de Luyten",
    "Étoile de Plaskett",
    "Étoile de Schweizer-Middleditch",
    "Étoile de Teegarden",
    "Étoile de van Maanen",
    "Ettanin",
    "Fakt",
    "Falx Italica",
    "Fekda",
    "Ferkad",
    "Fidis",
    "Fom",
    "Fomal'gaut",
    "Fomalhaut",
    "Fomal'khaut",
    "Foramen",
    "Fum al Samakah",
    "Furud",
    "Gacruks",
    "Gacrux",
    "Gainsar",
    "Gallina",
    "Gamal'",
    "Gemma",
    "Genam",
    "Gianfar",
    "Giansar",
    "Giausar",
    "Giauzar",
    "Giena",
    "Gienah",
    "Giénah",
    "Gienah Corvi",
    "Gienah Cygni",
    "Gienah Ghurab",
    "Gienakh",
    "Gildun",
    "Girtab",
    "Gnedi",
    "Gnosia",
    "Gnosia Stella Coronae",
    "Gomeïsa",
    "Gomejsa",
    "Gomejza",
    "Gomelza",
    "Gorgona",
    "Gorgonea Quarta",
    "Gorgonea Prima",
    "Gorgonea Secunda",
    "Gorgonea Tertia",
    "Graffias",
    "Xi Scorpii",
    "Grafias",
    "Zêta2 Scorpii",
    "Granatovaya",
    "Grassias",
    "Gredi",
    "Grenat",
    "Grumium",
    "Hadar",
    "Haedi",
    "Haedus",
    "Haedus I",
    "Haedus II",
    "Hamal",
    "Hamul",
    "Haris",
    "Haris-el-sema",
    "Hassaleh",
    "Hatysa",
    "Heka",
    "Hemal",
    "Hercule",
    "Heze",
    "Hoedus I",
    "Hoedus II",
    "Homam",
    "Homan",
    "Humam",
    "Hyadum I",
    "Hyadum II",
    "Hydor",
    "Icalurus",
    "Iclarkrau",
    "Inkalunis",
    "Isida",
    "Isis",
    "Izar",
    "Jabbah",
    "Jed",
    "Jed Posterior",
    "Jed Prior",
    "Jildun",
    "Juza",
    "Kabalraï",
    "Kabeleced",
    "Kaf",
    "Kaff",
    "Kaffa",
    "Delta Ursae Majoris",
    "Kaffalidma",
    "Kaffaljidhma",
    "Kaitain",
    "Kajam",
    "Kakkab",
    "Kalb",
    "Kal'b",
    "Kalb al Akrab",
    "Kalbelaphard",
    "Kantajn",
    "Kanopus",
    "Kapella",
    "Kastor",
    "Kastra",
    "Kaus Australis",
    "Kaus Borealis",
    "Kaus Media",
    "Kaus Medius",
    "Kaus Meridianalis",
    "Kaus Meridionalis",
    "Keïd",
    "Kelb Alraï",
    "Kerb",
    "Khadar",
    "Khamal'",
    "Khan",
    "Khara",
    "Kheka",
    "Kheze",
    "Khomam",
    "Khort",
    "Kied",
    "Kiffa Australis",
    "Kiffa Borealis",
    "Kinosura",
    "Kital'fa",
    "Kital'fia",
    "Kitalpha",
    "Kitalphar",
    "Kitel Phard",
    "Kkhambaliya",
    "Kocab",
    "Kochab",
    "Kochah",
    "Kokhab",
    "Kor Karoli",
    "Korneferos",
    "Kornephoros",
    "Krats",
    "Kraz",
    "Ksora",
    "Kullat Nunu",
    "Kuma",
    "Kurhah",
    "Kursa",
    "Labr",
    "La Superba",
    "Lesath",
    "Lesuth",
    "Lezakh",
    "Lezat",
    "Lucida Cymbae",
    "Maasym",
    "Mabsuthat",
    "Maïa",
    "Majya",
    "Manubrij",
    "Marchab",
    "Marfak",
    "Kappa Herculis",
    "Mu Cassiopeiae",
    "Thêta Cassiopeiae",
    "Marfic",
    "Marfik",
    "Lambda Ophiuchi",
    "Marj",
    "Markab",
    "k1 Puppis",
    "Tau Pegasi",
    "Markeb",
    "k Velorum",
    "Marrha",
    "Marsik",
    "Masym",
    "Matar",
    "Meboula",
    "Mebsuta",
    "Media",
    "Megrets",
    "Megrez",
    "Meïssa",
    "Mejssa",
    "Mekbuda",
    "Melucta",
    "Men",
    "Menchib",
    "Menka",
    "Menkab",
    "Menkalina",
    "Menkalinan",
    "Menkar",
    "Lambda Ceti",
    "Menkent",
    "Menkhib",
    "Menkib",
    "Xi Persei",
    "Zêta Persei",
    "Mentar",
    "Merach",
    "Merak",
    "Merakh",
    "Meres",
    "Merets",
    "Merez",
    "Merga",
    "Merkab",
    "Meropa",
    "Mérope",
    "Mesarthim",
    "Mesartkhim",
    "Mesartim",
    "Metallah",
    "Metallakh",
    "Mezartim",
    "Miaplacidus",
    "Miaplatsidus",
    "Mifrid",
    "Mimosa",
    "Mimoza",
    "Minchir",
    "Minelauva",
    "Delta Virginis",
    "Minkar",
    "Mintaka",
    "Mintika",
    "Mira",
    "Miram",
    "Mirac",
    "Epsilon Bootis",
    "Mirach",
    "Mirak",
    "Bêta Ursae Majoris",
    "Mirakh",
    "Mirfak",
    "Mirphak",
    "Mirtsam",
    "Mirza",
    "Gamma Canis Majoris",
    "Zêta Ursae Majoris",
    "Mirzam",
    "Mismar",
    "Misam",
    "Kappa Persei",
    "Lambda Herculis",
    "Mitsar",
    "Mizar",
    "Mizat",
    "Monkar",
    "Motallakh",
    "Mothallah",
    "Mufrid",
    "Mufride",
    "Muhlifaïn",
    "Mulipheïn",
    "Muliphen",
    "Muphrid",
    "Muphride",
    "Murfach",
    "Murzim",
    "Muscida",
    "Pi1 Ursae Majoris",
    "Pi2 Ursae Majoris",
    "Na'ir al Saïf",
    "Naïr al Saïf",
    "Naïr al Zaurak",
    "Naos",
    "Nash",
    "W Sagittarii",
    "Nashira",
    "Nat",
    "Nath",
    "Natkh",
    "Navigatoria",
    "Nekkar",
    "Nibal",
    "Nicolaus",
    "Nihal",
    "Nikhal'",
    "Nod",
    "Nodus I",
    "Zêta Draconis",
    "Nodus II",
    "Nodus Secundus",
    "Nunki",
    "Nusakan",
    "Nushaba",
    "Oculus Boreus",
    "Okda",
    "Okul",
    "Os Pegasi",
    "Os Piscis Meridiani",
    "Os Piscis Notii",
    "Palilicium",
    "Palilistij",
    "Paliliya",
    "Paon",
    "Parilicium",
    "Pelag",
    "Perse",
    "Phacd",
    "Phact",
    "Phad",
    "Phaet",
    "Phakt",
    "Phecda",
    "Phegda",
    "Phekda",
    "Phekha",
    "Pherkad",
    "Pherkad Major",
    "Pherkad Minor",
    "Pherkard",
    "Phurud",
    "Pikok",
    "Pish Pai",
    "Pléione",
    "Plejone",
    "Plejona",
    "Polaris",
    "Polaris Australis",
    "Polaris Galacticus Borealis",
    "Polis",
    "Polluks",
    "Pollux",
    "Polyarnaya",
    "Porrima",
    "Praecipua",
    "Praepes",
    "Praesepe",
    "Prezepe",
    "Prima Giedi",
    "Printseps",
    "Procyon",
    "Propus",
    "Protrigetrix",
    "Protrygetor",
    "Provindemiator",
    "Proksima",
    "Proksima Kentavra",
    "Proxima Centauri",
    "Prop",
    "Êta Geminorum",
    "Iota Geminorum",
    "Protsion",
    "Pulcherrima",
    "Rana",
    "Rana Secunda",
    "Rasaben",
    "Rasalas",
    "Ras al Asad al Shamaliyy",
    "Ras alegti",
    "Ras Al'geti",
    "Ras Algethi",
    "Rasalgethi",
    "Ras Alhague",
    "Rasalhague",
    "Ras Al'khag",
    "Rasal'khag",
    "Ras Al'khage",
    "Ras al Muthallah",
    "Ras Elased Australis",
    "Ras Elased Borealis",
    "Rasehl'gul",
    "Ras Hammel",
    "Rastaban",
    "Gamma Draconis",
    "Rastaben",
    "Ras Thaoum",
    "Reda",
    "Regor",
    "Regul",
    "Régulus",
    "Rescha",
    "Resha",
    "Rigel",
    "Rigel'",
    "Rigel Kentaurus",
    "Rigil Kent",
    "Rigil' Kentavrus",
    "Rijl al Awwa",
    "Rotanen",
    "Rotanev",
    "Rucba",
    "Rucha",
    "Ruchba",
    "Oméga2 Cygni",
    "Ruchbah",
    "Epsilon Cassiopeiae",
    "Rukba",
    "Rukbat",
    "Rukbat al-dajajah",
    "Rukbat al Rami",
    "Rutilicus",
    "Saad el Melik",
    "Saad el Sund",
    "Sabik",
    "Saclateni",
    "Sadachbia",
    "Sadalachbia",
    "Sadalbari",
    "Sadal'melek",
    "Sadalmelek",
    "Sadal'melik",
    "Sadalmelik",
    "Sadalsud",
    "Sadalsund",
    "Sadalsuud",
    "Sadatoni",
    "Sad Ehl'zud",
    "Sad es Saud",
    "Sadir",
    "Sadira",
    "Sadlamulk",
    "Sador",
    "Sadr",
    "Saïdak",
    "Saïf",
    "Saïf al Jabbar",
    "Saïph",
    "Salm",
    "Sargas",
    "Sarin",
    "Sartan",
    "Scalovin",
    "Sceptrum",
    "Scheat",
    "Delta Aquarii",
    "Schedar",
    "Scheddi",
    "Schedir",
    "Scutulum",
    "Seat Alpheras",
    "Secunda Giedi",
    "Seat",
    "Segin",
    "Seginus",
    "Serdtse Carla",
    "Sertan",
    "Shaf",
    "Sham",
    "Sharatan",
    "Shaula",
    "Sheat",
    "Shedar",
    "Sheddi",
    "Shedir",
    "Shéliak",
    "Shelyak",
    "Shératan",
    "Shiliak",
    "Sinistra",
    "Sirius",
    "Sirah",
    "Sirrah",
    "Sirrakh",
    "Situla",
    "Skat",
    "Soleil",
    "Spica",
    "Spica Virginis",
    "Spika",
    "Stérope I",
    "Stérope II",
    "Sualocin",
    "Sualotsin",
    "Subra",
    "Suhaïl",
    "Lambda Velorum",
    "Suhaïl al Muhlif",
    "Suhaïl Hadar",
    "Suhel",
    "Sukhejl'",
    "Sulafat",
    "Sulaphat",
    "Svalocin",
    "Syrma",
    "Tabit",
    "Upsilon Orionis",
    "Tajgeta",
    "Talita",
    "Talitha",
    "Tania Australis",
    "Tania Borealis",
    "Tarazed",
    "Tarf",
    "Taygeta",
    "Taygète",
    "Tegmen",
    "Tegmine",
    "Tejat",
    "Tejat Posterior",
    "Tejat Prior",
    "Terebell",
    "Terebellum",
    "60 Sagittarii",
    "62 Sagittarii",
    "Oméga Sagittarii",
    "Teyat Posterior",
    "Teyat Prior",
    "Thabit",
    "Theemim",
    "Theemin",
    "Thuban",
    "Toliman",
    "Torcularis Septentrionalis",
    "Tramontana",
    "Tsebal'raj",
    "Tselano",
    "Tsel'bal'raj",
    "Tselena",
    "Tsih",
    "Tsolma",
    "Tuban",
    "Turaïs",
    "Tureis",
    "Tyl",
    "Unuk",
    "Unuk alb Khaj",
    "Unukalhaï",
    "Unuk al Hay",
    "Unukalhay",
    "Unuk al' Khaj",
    "Unuk Ehl'khaja",
    "Unuk Elhaia",
    "Urkab",
    "Vasat",
    "Véga",
    "Venabulum",
    "Venatici",
    "Vendémiatrix",
    "Venator",
    "Vespertilio",
    "Vezad",
    "Vezen",
    "Vildiur",
    "Vindemiator",
    "Vinde-Miatriks",
    "Vindemiatriks",
    "Vindémiatrix",
    "Wasat",
    "Wazn",
    "Wéga",
    "Wesat",
    "Wesen",
    "Wezn",
    "Wezen",
    "Yad",
    "Yed",
    "Yed Posterior",
    "Yed Prior",
    "Yildun",
    "Yilduz",
    "Zaniah",
    "Zannakh",
    "Zarijan",
    "Zaurac",
    "Zaurack",
    "Zaurak",
    "Zavidzhava",
    "Zavijah",
    "Zavijava",
    "Zavyava",
    "Zawijah",
    "Zibal",
    "Zosca",
    "Zosma",
    "Zozca",
    "Zozma",
    "Zuben Ehl'genubi",
    "Zuben Ehl' Genubi",
    "Zuben Elakrab",
    "Zuben Elakribi",
    "Zuben El Chamali",
    "Zubenelg",
    "Zuben el Genubi",
    "Zuben Elgenubi",
    "Zubenelgenubi",
    "Zuben el Hakrabi",
    "Zuben Elschemali",
    "Zuben Eschamali",
    "Zubenesch",
    "Zubeneschamali",
    "Zubenish",
    "Zuben Hakrabi",
    "Gamma Scorpii",
    "Zuben Hakraki",
    "Zubenhakraki",
    "Sigma Librae",
    "Zubal Al Akrab",
    "Zubra",
    "Zujj al Nushshabah"
];
